### ISSUE TITLE
Add a not supported pre-commit-hook

### ISSUE THREAD

**Issue by albertodvp** [input-output-hk/iogx#33]
Hello😌 
From the [documentation](https://github.com/input-output-hk/iogx/blob/main/doc/api.md#mkshellinprecommit), I see `iogx` does not currently support all the hooks that _pre-commit-hooks.nix_ supports, I'm interested in adding some [nix hooks](https://github.com/cachix/pre-commit-hooks.nix?tab=readme-ov-file#nix-1) in a project that is based on `iogx`, any advice on how I can achieve that without "hacking" the template usage?

**Comment by zeme-wana** [comment]
Hello @albertodvp, sorry for the late reply. You raised a valid point. There is currently no easy way to do what you're asking. However this would be a very useful feature, so I'll be making a PR for this.

**Comment by zeme-wana** [comment]
Closed by https://github.com/input-output-hk/iogx/pull/38
