### ISSUE TITLE
Flake templates: Description for commented out code

### ISSUE THREAD

**Issue by Rosuavio** [input-output-hk/iogx#34]
Descriptions above any commented out code in the flake templates would help a lot for quickly starting up a new project, especially for someone who has not used IOGx before, and for someone who has but might not know what specific commented out code would do when it is using a new option.

**Comment by Rosuavio** [comment]
I recognize, that most of everything is documented already in the IOGx repo, this would be a convince that lines up with the convince of the flake templates.

**Comment by zeme-wana** [comment]
The template files in the latest version of iogx contain comments with links to docs for each major function. 
This is a good compromise: commenting every option would mean duplicating documentation in two places.
