### ISSUE TITLE
nixosModules and nixosConfigurations

### ISSUE THREAD

**Issue by klarkc** [input-output-hk/iogx#39]
Currently, there is no way beyond passing them in `mkFlake` flake attribute. It would be nice to have the same structure of outputs to provide NixOS modules. This is what it looks like to provide NixOS modules and configs right now (not so pretty):

```nix
let
  #...
  nixos = import ./nixos.nix inputs self;
in
inputs.iogx.lib.mkFlake {
  inherit inputs systems;
  repoRoot = ./.;
  outputs = import ./nix/outputs.nix;
  flake = {
    inherit (nixos) nixosConfigurations nixosModules;
  };
};
```

A possible approach, since outputs represent system-dependent outputs, is to add `mkFlake` another option, `nixos`, with a payload as an "extension" of the standard NixOS modules payload.

Or even better, allow `flake` to be a function (like `outputs`) receiving the same attributes (excepting `system`), so we can extend the `outputs` features to not system-dependent outputs.

**Comment by zeme-wana** [comment]
> Or even better, allow flake to be a function (like outputs) receiving the same attributes (excepting system), so we can extend the outputs features to not system-dependent outputs.

Good advice, I did this in https://github.com/input-output-hk/iogx/pull/48
(but the only attributes available can be `{ repoRoot, inputs }`)
