### ISSUE TITLE
Upgrade cabal-fmt to 0.1.12

### ISSUE THREAD

**Issue by koslambrou** [input-output-hk/iogx#80]
The current `cabal-fmt` version is at `0.1.7`, and I tried upgrading it to `0.1.12`.

However, after applying that change, I tried creating a template IOGX repository (with `nix flake init --template ./iogx#haskell`), and checked the `cabal-fmt` version (with `cabal-fmt --version`). However, it still showed `0.1.7`.

Did I miss something?

**Comment by zeme-wana** [comment]
I will upgrade cabal-fmt in iogx. 
Meanwhile, can you show me exactly how you tried upgrading?

**Comment by koslambrou** [comment]
I didn't try upgrading it in my repo. I just created a new IOGX template from scratch (with the command above), and checked the `cabal-fmt` version which still showed `0.1.7`.

**Comment by zeme-wana** [comment]
Implemented by https://github.com/input-output-hk/iogx/pull/81
